### PR TITLE
extend Metar constructor `strict` to cover all `ParserError`s

### LINKED ISSUE #51: Allow `ParserErrors` to not raise
If you're like me and get most of your METAR codes from FAA's ASOS program, you get a *lot* of parser errors.

The `MetarParser` subclass in [cloudside](https://github.com/Geosyntec/cloudside/blob/master/cloudside/station.py#L149) gets around this by simply logging the error and moving on. 

It'd be nice to have this as an *option* upstream.

### PR DESCRIPTION
**Pull request by akrherz**
closes #51

### CODE REVIEW

**Comment by akrherz** [comment]
Adding a test here that actually generates an exception is rather funny, since if we have parsing code that raises exceptions, we should fix that bug! :slightly_smiling_face:

**Comment by akrherz** [comment]
I have a test in and realize now that known Exceptions can come from other places than just Metar, this all will take some consideration for the API.

**Comment by akrherz** [comment]
Thanks @phobson , I'd like to see if @WeatherGod chimes in on this prior to merging.  Will wait a bit while I work on a PR for a formal release.  Or are we still not close enough for what you need for cloudside to use?

**Comment by phobson** [comment]
To clear: strictly speaking, this change is not necessary for cloudside to function as intended, but may help preventing ASOS's weirder codes from being completely ignored.

Punting on this in favor of more robust error handling would be fine by me.

**Comment by akrherz** [comment]
Thanks @phobson , this change does not impact previous code behavior, so will take this PR now so to proceed with a release.

**Pull request merged**
