### PR TITLE
add ParserError to type stub

### PR DESCRIPTION
**Pull request by MatthewFlamm**
ParserError is missing from type stubs and it causes errors in downstream type checking.  See https://github.com/MatthewFlamm/pynws/pull/109.

I don't see any type checking on your CI, but it passes a mypy check when run locally.

### CODE REVIEW

**Comment by akrherz** [comment]
Thank you.  Are you able to add a CI check here for us as well?

**Comment by MatthewFlamm** [comment]
> Thank you. Are you able to add a CI check here for us as well?

I can do that.  I see the current pytest is done through conda and directly coding in installing dependencies in the workflow.  If I create a `requirements-typing.txt` and pin mypy version there, you could use dependabot to control updates.  Or keep it simple and just install the latest?

**Comment by akrherz** [comment]
> Or keep it simple and just install the latest?

I think you are more knowledgeable and defer to your judgement for what is best.

**Comment by MatthewFlamm** [comment]
Added. Im not super familiar with type stubs, but I believe these are only used to signal to downstream applications.  I'm not sure that you get the benefit (and pain) of type checking the code inside this package.  This is outside the scope of this PR, just wanted to point this out for consideration.

**Comment by gamecss** [comment]
Sorry :)

**Pull request merged**
