### PR TITLE
fix: add code translation to no significant weather, nsw

### PR DESCRIPTION
**Pull request by JordonMaule**
Code tested: VEIM 301200Z 16007KT 7000 NSW SCT018 31/27 Q1007 NOSIG
Before:
image

After:
image

### CODE REVIEW

**Comment by phobson** [comment]
Thanks for PR, @JordonMaule . Do you happen to know if any other keys are missing from that dictionary?

Could you add your example as a test in the test suite?

**Comment by JordonMaule** [comment]
@phobson Thank you for your quick reply. 
I believe the 'other' codes are all covered.

Most times NSW appear on the end of the code, and is not recognized. (Haven't had the time to review this yet)
But if it's on the middle of the bulletin it matched with the Regex from line 77, and we didn't have the key on WEATHER_OTHER. 

I've added tests to all the keys in WEATHER_OTHER, if you'd prefer to have only the NSW code tested let me know and I'll remove the others.

**Comment by phobson** [comment]
@JordonMaule thanks for the test, looks great!

**Review by phobson — APPROVED** [review]

**Review by akrherz — APPROVED** [review]
Thanks for improving the tests!

**Pull request merged**
