### PR TITLE
Enable parsing of METARs that list wind and visibility after the sky condition groups.

### LINKED ISSUE #147: Unparsed group '09008KT 7SM' when wind is listed after sky groups.
The following METAR produces a ParserError:

METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186

Backtrace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jhaiduce/Development/python-metar/metar/Metar.py", line 499, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body '09008KT 7SM' while processing 'METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186'
```

### PR DESCRIPTION
**Pull request by jhaiduce**
Add an extra copy of the wind and visibility, to enable parsing of METARs that list wind and visibility after the sky condition groups.

Fixes #147.

### CODE REVIEW

**Review by akrherz — APPROVED** [review]
This seems like a reasonable workaround, but await other's comments.

**Review by phobson — APPROVED** [review]
This looks good to me as well.

**Comment by akrherz** [comment]
sorry @jhaiduce , do you mind resolving the conflicts?  if not, I can do it, no worries.

**Comment by jhaiduce** [comment]
> sorry @jhaiduce , do you mind resolving the conflicts? if not, I can do it, no worries.

Done. Should be mergeable now.

**Pull request merged**
