### PR TITLE
to_dict

### PR DESCRIPTION
**Pull request by kclosu**
key-value form of the report for export to db, for example

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks for submitting this code!  My initial reactions are:

 - dictionary keys get named differently than the object attribute names.  I am unsure if this is a good idea or not.
 - Some attribute values are translated into unitless quantities.
 - It would be nice to see a unit test added for this, is that something you can effort?

**Comment by phobson** [comment]
Gave this some thought. I think it makes the most since to make a mixin for all of the quantities in Datatypes.py. Something like:

```python
# classes representing dimensioned values in METAR reports
class _QuantityMixin(object):
    def to_dict(self, units=None):
        units_to_use = units or self._units
        _compass = {'compass': self.compass()} if hasattr(self, 'compass') else {}
        _trace = {'istrace': self.istrace()} if hasattr(self, 'istrace') else {}
        if self.value():
            result = {
                'value': self.value(units=units_to_use),
                'units': units_to_use,
                'string': self.string(units=units_to_use),
            }
            result.update(_compass)
            result.update(_trace)
            return result
```

Then if everything subclassess the mixin, e.g.:
```python
class temperature(_QuantityMixin):
    # yada

class pressure(_QuantityMixin):
    # yada

class precipitation(_QuantityMixin):
    # yada
```

Then this PR could loop through all of the attributes of the Metar object, check that has a `to_dict` method, and assign that to its respective key in the dictionary.

You wouldn't end up with a flat dictionary, but that'd be easy to get too (`flat = {k: d[k]['value'] for k in metar_dict}`).

**Comment by LawrsB** [comment]
Hello,

My name is Lawrence Blundo. I am a senior meteorology major at Embry-Riddle Aeronautical University. I am sorry to bother you guys, but I am having trouble figuring out exactly how the Metar.py package exactly works. Would someone be willing to help me out with properly figuring out this package?

**Comment by phobson** [comment]
@LawrsB This is an issue related to converting a metar object to a dictionary.

We have an example of using the library in the readme file here:
https://github.com/python-metar/python-metar#example

If the installation instructions and example don't answer your question, open a different issue related to the documentation.

**Comment by diegogarromolina** [comment]
I'm tempted for make a pull request like `to_json()` method, because it is the most popular format on the web and mobile apps to share data. What do you think about this?

**Comment by akrherz** [comment]
> I'm tempted for make a pull request like `to_json()` method,

In general, nobody here will object when somebody offers to volunteer to do some work :)  This code isn't being pushed very hard for development, as at least for me, I hope that [Unidata/MetPy](https://github.com/Unidata/MetPy)'s recently added METAR parser can help consolidate efforts.

**Comment by akrherz** [comment]
Sorry, I'm going to close this out as stalled / not desired for implementation in the current form.

**Pull request closed without merging**
