### PR TITLE
Improved docs as well as making docs looks attractive.

### PR DESCRIPTION
**Pull request by ovs1176**

### CODE REVIEW

**Review by tomp — COMMENTED** [review]
This neither improves the docs nor makes them more attractive.

**Comment by ovs1176** [comment]
Please accept my pull request after that change it.

Please i am doing this due to a contest hacktoberfest in which they gift a
t shirt
In my opinion you may also try by which you may also get free t shirt.
So please accept my pull request.
Please please sir🙏🙏🥺🥺

**Comment by akrherz** [comment]
Hi @ovs1176, thanks for the attempt here.  You can add commits to your branch, which is unfortunately master in this case, which will make things harder.  You may want to first create a feature branch, do your commits there and then submit that branch as a pull request.

**Comment by ovs1176** [comment]
Actually sir I am noob in programming and I just enroll in a contest named hackoctberfest in which they are giving free t shirts in just 4 pull requests so sir please accept my pull request after that change it as you want..Thanku sir.Please sir accept that request.🙏🙏🥺🥺😷😷Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: daryl herzmann <notifications@github.com> Date: 01/10/2020  2:01 am  (GMT+05:30) To: python-metar/python-metar <python-metar@noreply.github.com> Cc: ovs1176 <ovs1176@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [python-metar/python-metar] Improved docs as well as making docs looks attractive. (#111) 
Hi @ovs1176, thanks for the attempt here.  You can add commits to your branch, which is unfortunately master in this case, which will make things harder.  You may want to first create a feature branch, do your commits there and then submit that branch as a pull request.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/python-metar/python-metar/pull/111#issuecomment-701628288",
"url": "https://github.com/python-metar/python-metar/pull/111#issuecomment-701628288",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by akrherz** [comment]
Sorry, that's not how this works and actually against the terms of the hacktober fest you signed up for.  See the verbiage about pull request quality.

**Comment by ovs1176** [comment]
sorry, sir for your disturbance.

**Pull request closed without merging**
