### PR TITLE
Fix Haversine formula in position class (Datatypes.py)

### PR DESCRIPTION
**Pull request by diegogarromolina**
The correct formula has sin²(angle).

### CODE REVIEW

**Review by phobson — CHANGES_REQUESTED** [review]
@diegogarromolina  thanks for the PR. The CI failure you're seeing is related to our python 3.7 Travis configuration and not your PR. 

Could you add a test to the test suite that confirms that this is producing the desired results?

**Comment by diegogarromolina** [comment]
Sorry, but the documentation is not clear at position class. Long and Lat in the constructor are floats, but to compute `a`, the functions `cos` and `sin` needs a value in radians. I seen that you don't make a test for position before in `test` folder. Do you tested that computes? I take this repo as an inspiration to develop a metar parser in Dart language, and I seen the error on Haversine formula while writing the Position class in that language. Thanks.

**Comment by tomp** [comment]
The methods of the datatypes.position class are dead code, really.  They have never been used for anything.  I would be inclined to delete the getdistance() and getdirection() methods, rather than fix them.

**Comment by diegogarromolina** [comment]
Like I said above, I develop the correct computes in Dart, but you got a good point, they have never been used for anything. If you delete them, then I don't make a PR. Thanks

**Comment by akrherz** [comment]
I rebased this just to see what CI / codecov says.  I am inclined to take this PR and then cull the unused API with a subsequent PR.  We likely don't have any contract with what our library's public API is and we are still at version 0.x :)

**Pull request merged**
