### PR TITLE
Corrections to position class.

### PR DESCRIPTION
**Pull request by mkjunker**
* Was missing '*' in line 483.
* Arguments to trig functions should be in radians.
* Output of getdirection should be in degrees.
* atan2 call at line 486.
* Earth radius was off by factor of 10.

### CODE REVIEW

**Comment by mkjunker** [comment]
I made a mistake somewhere.  Need to track it down.

**Comment by mkjunker** [comment]
Was missing '*' in line 483.
Arguments to trig functions should be in radians.
Output of getdirection should be in degrees.
atan2 call at line 486.
Earth radius was off by factor of 10.

**Comment by akrherz** [comment]
Hi @mkjunker , sorry that your PR got no feedback.  Could you kindly rebase it and add some tests to exercise the API?

**Comment by akrherz** [comment]
Sorry for the troubles @mkjunker , your merge didn't appear to work out.

**Comment by mkjunker** [comment]
I wasn't done updating my fork.  The position.getdistance function was removed from the main repo with a commit comment that it isn't used.  It appears the position.getdirection function isn't used either.  I started writing a test and noticed that the use of math.pi won't work, because math is not imported.  Also, position's __str__ function fails because position.string() isn't defined.  If no one else wants getdistance and getdirection, I can keep working off my fork.  If there is interest in using them, I can fix them for merging into this repo.

**Comment by akrherz** [comment]
@mkjunker Thanks.  In general, all bugs are good to fix :)  One item here though is that you should create a branch on your fork prior to making changes and then submit your PR from that branch.  When you place commits on your forked master/main branch, it is difficult to maintain.

**Pull request closed without merging**
