### PR TITLE
denote release 1.8.0

### PR DESCRIPTION
**Pull request by akrherz**
refs #126

### CODE REVIEW

**Review by phobson — APPROVED** [review]

**Comment by phobson** [comment]
@akrherz FWIW, the GH action to handle releases on pypi is pretty handy. see here: https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-publish.yml

**Comment by akrherz** [comment]
@tomp, you OK with making a release?

**Comment by tomp** [comment]
Sure.  I trust you, completely, to make the right decisions about this sort
of thing.

**Comment by akrherz** [comment]
Thanks @tomp for the vote of confidence.  I have updated the release date in the `CHANGELOG.md` and will go forward with the release once CI passes.  Will incorporate the Github Action for PyPi for the next release :)

**Pull request merged**
