### PR TITLE
fix getdistance

### PR DESCRIPTION
**Pull request by jdkloe**
fix getdistance by properly implementing Haversine equation and add a test case.
This should also fix issue #109

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks for your PR!  In #110, we discussed removing this API as it is not used internally.  Are you using it?

**Comment by jdkloe** [comment]
Thanks for your reply. I seem to have overlooked PR #110.
No at the moment I don't use this interface, but I noticed warnings when running the pytest sequence, and also the conversion to bytecode causes warnings on this code.
As I am packaging the metar module for Fedora I see this kind of warnings pass by, so wanted to fix them.
Anyway, if you decide these interfaces are not useful I don't feel strong about keeping them. Feel free to remove them.

**Comment by akrherz** [comment]
Hi @phobson , what do you think of removing this code entirely?

**Comment by phobson** [comment]
I certainly never use it. 👍🏻 from me

**Comment by akrherz** [comment]
Thanks again for your effort here @jdkloe , we removed the API as discussed within #155

**Pull request closed without merging**
