### PR TITLE
denote 1.9.0 release

### PR DESCRIPTION
**Pull request by akrherz**

### CODE REVIEW

**Review by phobson — APPROVED** [review]
I'm ok with this. 

I remembered that on my mpl-probscale repo, I have a github workflow that publishes a new release to pypi. 

https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-publish.yml

Would it be worth moving that over before we do this?

**Comment by akrherz** [comment]
@phobson Thanks, I never object when people offer to do work :)  If you are wanting me to make this magic happen, then likely not before this release.

**Comment by phobson** [comment]
@akrherz totally. I can give it a shot, Just wanted to offer it up.

Do you mind if I push a commit up to this branch that updates the python version meta data in setup.py? Currently says metar supports python >= 2.5 😭

**Comment by akrherz** [comment]
> Do you mind if I push a commit up to this branch that updates the python version meta data in setup.py?

Sure, go for it.

**Comment by akrherz** [comment]
force pushed to update release date.

**Pull request merged**
