### PR TITLE
Enable parsing of METARs that list sea level pressure after the altimeter setting rather than in the remarks.

### LINKED ISSUE #148: Unparsed group 'SLP162' when SLP group placed ahead of remarks group.
The following METAR produces a ParserError:

METAR KCOF 191855Z 18015G22KT 7SM FEW049 SCT300 28/18 A3001 SLP162 RMK WND DATA ESTMD

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jhaiduce/Development/python-metar/metar/Metar.py", line 499, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body 'SLP162' while processing 'METAR KCOF 191855Z 18015G22KT 7SM FEW049 SCT300 28/18 A3001 SLP162 RMK WND DATA ESTMD'
```

### PR DESCRIPTION
**Pull request by jhaiduce**
Although sea level pressure (SLP) groups are normally found in the remarks section, in rare cases the SLP group can be found after the altimeter setting. This PR allows enables parsing of METARs that are structured in this way.

Fixes #148.

### CODE REVIEW

**Review by akrherz — APPROVED** [review]
Seems harmless to me, but am looking for other's comments.

**Comment by tomp** [comment]
I don't think this would break anything.  That said, I be reluctant make a change like this to fix a single instance. Are there other stations submitting reports with SLP treated like this?  We already have many exceptions for various types of non-conforming METAR reports in this module, but generally I'd only consider doing that if the error was reasonably common.

**Comment by jhaiduce** [comment]
>  Are there other stations submitting reports with SLP treated like this?

I've only encountered one METAR with this structure.

**Comment by tomp** [comment]
I think it's probably fine to merge this, because it should be easy for later maintainers to understand how and why this was done.

If I were still working with this kind of data, I'd be tempted to add a "strict mode", that would accept only METAR that followed the WMO or US spec.  If nothing else, it would be a way of documenting - in the code - what changes were made to accommodate non-conforming reports, in case any of those ever cause problems.

**Comment by jhaiduce** [comment]
> If I were still working with this kind of data, I'd be tempted to add a "strict mode", that would accept only METAR that followed the WMO or US spec. If nothing else, it would be a way of documenting - in the code - what changes were made to accommodate non-conforming reports, in case any of those ever cause problems.

There already is a "strict" argument passed Metar.Metar constructor. But currently it just changes the error handling behavior (whether to throw exceptions or issue warnings). How much the parser tolerates deviations from the spec(s) should probably be handled with a separate option.

**Comment by tomp** [comment]
Sure.  In any case, to create what I was suggesting, I think you'd need to create a "strict" version of the group regex's and group-regex list.  Most of the other accommodations for non-conforming METAR were made in those regex's.  I can't imagine anyone's going to want to do that, anytime soon.

**Pull request merged**
